---
name: LuaCheck

on: 
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  LuaCheck:
    name: LuaCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install LuaCheck
        run: apt install lua-check

      - name: Run LuaCheck
        run: |
          for $x in $(ls ./libs/*.lua); do 
            luacheck $x; 
          done