name: luci-openvpn-status-cicd

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: JohnnyMorganz/stylua-action@v4
          with:
            token: ${{ secrets.GH_TOKEN }}
            version: v2.1.0
            args: false

        - name: Make
          run: make clean build

        - name: Create Version
          id: pkg-version
          run: echo "pkg-version=luci-openvpn-status-$(cat ./MODULE_VERSION)-git-${{ github.sha }}" >> $GITHUB_OUTPUT

        - name: Upload versioned artifact
          uses: actions/upload-artifact@v4
          with:
            name: luci-openvpn-status
            path: ./build/${{ steps.pkg-version.outputs.pkg-version }}.tgz

  release:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref_type == 'tag'
        steps: 
        - name: Download a single artifact
          uses: actions/download-artifact@v4
          with:
            name: luci-openvpn-status

        - uses: softprops/action-gh-release@v2
          with:
            files: luci-openvpn-status/*

