name: luci-openvpn-status-cicd

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: JohnnyMorganz/stylua-action@v4
          with:
            token: ${{ secrets.GH_TOKEN }}
            version: v2.1.0
            args: false
            
        - name: Make
          run: make clean build
          
        - name: Release  
        - uses: softprops/action-gh-release@v2
          if: github.ref_type == 'tag'
          with:
              files: ./build/*.tgz
  
