name: luci-openvpn-status-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: JohnnyMorganz/stylua-action@v4
          with:
            token: ${{ secrets.GH_TOKEN }}
            version: v2.1.0
            args: false
        - name: Install dependencies
          run: sudo apt-get install -y lua5.1
        - name: Run Make
          run: make clean build
  
